sudo: required

arch:
    - amd64
    - arm64
services:
    - docker

before_install:
    - docker pull chubaofs/cfs-base:1.0

script:
    - sudo docker/run_docker.sh -l
    - sudo docker/run_docker.sh -t
